version: '3.12'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-journalblog}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-journalblog}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_ 